#pragma once

#include "alloc.h"
#include "assignment.h"
#include "bool_lit.h"
#include "definition.h"
#include "free.h"
#include "identifier.h"
#include "input.h"
#include "integer_lit.h"
#include "operation.h"
#include "root.h"
#include "relational_expression.h"
#include "string_lit.h"
#include "symbol.h"